version: '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Pa$$w0rd"
      POSTGRES_DB: "spmia_dev"
  configserver:
    extends:
      file: ../common/docker-compose.yml
      service: configserver
  licensingservice:
     image: mikebychkov/tmx-licensing-service:chapter3
     ports:
       - "8080:8080"
     environment:
       PROFILE: "dev"
       CONFIGSERVER_URI: "http://configserver:8888"
       CONFIGSERVER_PORT: "8888"
       DATABASESERVER_PORT: "5432"
