version: '2'
services:
  configserver:
    image: mikebychkov/tmx-confsvr:chapter3
    ports:
       - "8888:8888"
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"
  database:
    image: postgres:12.5
    restart: always
    environment:
      POSTGRES_USER: "postgres1"
      POSTGRES_PASSWORD: "Zxcv1234"
      POSTGRES_DB: "spmia_local"
  licensingservice:
    image: mikebychkov/tmx-licensing-service:chapter3
    depends_on:
      - configserver
      - database
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRIC"
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
