#example.property: "CONFIG SERVER IS UNAVAILABLE"

## JPA
#spring.jpa.generate-ddl: "false"
#spring.jpa.hibernate.ddl-auto: "none"
#spring.jpa.show-sql: "true"

## H2
#spring.h2.console.enabled: "true"

management:
  endpoints:
    web:
      exposure:
        include: "*"
