eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    rest:
      base-path: "/api"
  cloud:
    stream:
      bindings:
        #input:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
  redis:
    port: 6379
    host: localhost

security:
  oauth2:
    resource:
      user-info-uri: http://authenticationservice:8901/auth/user/
    client:
      grant-type: client_credentials

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.cloud: WARN
    org.mike: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"