server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  sensitive-headers: Cookie,Set-Cookie

spring:
  zipkin:
    base-url: "http://localhost:9411"

###################################################################################################

#zuul:
#  ignored-services: "*"
#  prefix: /api
#  routes:
#    licensingservice: /licensing/**
#    organizationservice: /organization/**

#zuul.debug.request: true
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 3000
#hystrix.command.licensingservice.execution.isolation.thread.timeoutInMilliseconds: 7000
#licensingservice.ribbon.ReadTimeout: 7000

management:
  endpoints:
    web:
      exposure:
        include: "*"
