eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8901
  servlet:
    context-path: /auth

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.mike: DEBUG

# TODO: OAUTH2+JWT https://www.baeldung.com/spring-security-oauth-jwt